FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["CompanyName.Ordering.Checkout.Api/CompanyName.Ordering.Checkout.Api.csproj", "CompanyName.Ordering.Checkout.Api/"]
RUN dotnet restore "CompanyName.Ordering.Checkout.Api/CompanyName.Ordering.Checkout.Api.csproj"
COPY . .
WORKDIR "/src/CompanyName.Ordering.Checkout.Api"
RUN dotnet build "CompanyName.Ordering.Checkout.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "CompanyName.Ordering.Checkout.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CompanyName.Ordering.Checkout.Api.dll"]
